spring:
  profiles:
    active: lower

  banner:
    location: logo-app

  h2:
    console:
      path: /h2-console
  datasource:
    generate-unique-name: false
    name: flashcards-database
    url: jdbc:h2:file:/db/flashcards
    username: jeremi
    password: 123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
